language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/simonjbeaumont/ocaml-travis-coveralls/master/travis-coveralls.sh
script:
    - bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - OCAML_VERSION=4.04
    - PACKAGE=message-switch
    - PINS="message-switch-async:. message-switch-cli:. message-switch-core:.  message-switch:.  message-switch-lwt:.  message-switch-unix:."
  matrix:
    - BASE_REMOTE=git://github.com/xapi-project/xs-opam#next XS_COV=1 COV_CONF="./configure" \
      TEST=false \
      POST_INSTALL_HOOK="env TRAVIS=$TRAVIS TRAVIS_JOB_ID=$TRAVIS_JOB_ID bash -ex .coverage.sh"
    - EXTRA_REMOTES=git://github.com/xapi-project/xs-opam#next
matrix:
    fast_finish: true
    allow_failures:
        - env: EXTRA_REMOTES=git://github.com/xapi-project/xs-opam#next

